// <auto-generated />
using System;
using ArqNetCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArqNetCore.Migrations
{
    [DbContext(typeof(ArqNetCoreDbContext))]
    [Migration("20200622063807_SuppliesOrders")]
    partial class SuppliesOrders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ArqNetCore.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(4000)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(4000)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ArqNetCore.Entities.Area", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("ArqNetCore.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("ArqNetCore.Entities.SuppliesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("AreaId")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32);

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AreaId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("SuppliesOrders");
                });

            modelBuilder.Entity("ArqNetCore.Entities.Supply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("SuppliesOrderId")
                        .HasColumnType("int");

                    b.Property<string>("SupplyTypeId")
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("SuppliesOrderId");

                    b.HasIndex("SupplyTypeId");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("ArqNetCore.Entities.SupplyAttribute", b =>
                {
                    b.Property<int>("SupplyId")
                        .HasColumnType("int");

                    b.Property<string>("AttributeName")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("AttributeValue")
                        .HasColumnType("text");

                    b.HasKey("SupplyId", "AttributeName");

                    b.ToTable("SupplyAttributes");
                });

            modelBuilder.Entity("ArqNetCore.Entities.SupplyType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SupplyTypes");
                });

            modelBuilder.Entity("ArqNetCore.Entities.SupplyTypeAttribute", b =>
                {
                    b.Property<string>("SupplyTypeId")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("AttributeName")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("AttributeDescription")
                        .HasColumnType("text");

                    b.HasKey("SupplyTypeId", "AttributeName");

                    b.ToTable("SupplyTypeAttributes");
                });

            modelBuilder.Entity("ArqNetCore.Entities.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ArqNetCore.Entities.SuppliesOrder", b =>
                {
                    b.HasOne("ArqNetCore.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("ArqNetCore.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("ArqNetCore.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");
                });

            modelBuilder.Entity("ArqNetCore.Entities.Supply", b =>
                {
                    b.HasOne("ArqNetCore.Entities.SuppliesOrder", "SuppliesOrder")
                        .WithMany()
                        .HasForeignKey("SuppliesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArqNetCore.Entities.SupplyType", "SupplyType")
                        .WithMany()
                        .HasForeignKey("SupplyTypeId");
                });

            modelBuilder.Entity("ArqNetCore.Entities.SupplyAttribute", b =>
                {
                    b.HasOne("ArqNetCore.Entities.Supply", "Supply")
                        .WithMany()
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArqNetCore.Entities.SupplyTypeAttribute", b =>
                {
                    b.HasOne("ArqNetCore.Entities.SupplyType", "SupplyType")
                        .WithMany()
                        .HasForeignKey("SupplyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArqNetCore.Entities.User", b =>
                {
                    b.HasOne("ArqNetCore.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
