openapi: "3.0.0"
info:
  description: ""
  version: "1.0.0"
  title: ""
  termsOfService: ""
  contact:
    email: "info@medical-supplies.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "supplies"
  description: "manage medical supplies distribution"
- name: "user"
  description: "manage user information"
- name: "organization"
  description: "manage organization information"
- name: "authentication"
  description: "Access control"
paths:
  /user/signup:
    post:
      tags:
      - "user"
      - "authentication"
      summary: "Register a new user"
      description: ""
      operationId: "userSignUp"
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignUpRequestDTO'
      responses:
        "405":
          description: "Invalid input"
        '201':
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSignUpResponseDTO'
  /user/signin:
    post:
      tags:
      - "user"
      - "authentication"
      summary: "Authorize an user"
      description: ""
      operationId: "userSignIn"
      requestBody:
        description: this pretends to be an alias for OAuth grant_type:client_credentials
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignInRequestDTO'
      responses:
        "405":
          description: "Invalid input"
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSignInResponseDTO'
  /user/refresh:
    post:
      tags:
      - "user"
      - "authentication"
      summary: "refresh authorization token"
      description: ""
      operationId: "userRefresh"
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRefreshRequestDTO'
      responses:
        "405":
          description: "Invalid input"
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRefreshResponseDTO'
  /user/profile:
    get:
      tags:
      - "user"
      summary: "user profile data"
      description: ""
      operationId: "userProfile"
      security: 
        - bearerJWT: []
      responses:
        "405":
          description: "Invalid input"
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponseDTO'
  /supplies-order:
    post:
      tags:
      - "supplies"
      summary: "create supplies order"
      description: ""
      operationId: "supplyCreate"
      security: 
        - bearerJWT: []
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuppliesOrderCreateRequestDTO'
      responses:
        "405":
          description: "Invalid input"
        '201':
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuppliesOrderCreateResponseDTO'
    get:
      tags:
      - "supplies"
      summary: "list supplies orders"
      description: ""
      operationId: "supplyList"
      security: 
        - bearerJWT: []
      parameters: 
      - name: status
        in: query
        description: status of order
        required: false
        schema:
          type: string
      responses:
        "405":
          description: "Invalid input"
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuppliesOrderListResponseDTO'
  /supplies-order/{suppliesOrderId}:
    get:
      tags:
      - "supplies"
      summary: "get supplies order by id"
      description: ""
      operationId: "supplyGetById"
      security: 
        - bearerJWT: []
      parameters: 
      - name: suppliesOrderId
        in: path
        description: ID of order
        required: true
        schema:
          type: string
      responses:
        "405":
          description: "Invalid input"
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuppliesOrderGetByIdResponseDTO'
  /supplies-order/supply-types:
    get:
      tags:
      - "supplies"
      summary: "available supply types"
      description: ""
      operationId: "suppliesOrderSupplyTypes"
      security: 
        - bearerJWT: []
      responses:
        "405":
          description: "Invalid input"
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuppliesOrderSupplyTypesResponseDTO'
  /supplies-order/accept:
    post:
      tags:
      - "supplies"
      summary: "accept an order and bind it to organization"
      description: ""
      operationId: "suppliesOrderAccept"
      security: 
        - bearerJWT: []
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuppliesOrderAcceptRequestDTO'
      responses:
        "405":
          description: "Invalid input"
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuppliesOrderAcceptResponseDTO'
  /supplies-order/reject:
    post:
      tags:
      - "supplies"
      summary: "reject an order"
      description: ""
      operationId: "suppliesOrderReject"
      security: 
        - bearerJWT: []
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuppliesOrderRejectRequestDTO'
      responses:
        "405":
          description: "Invalid input"
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuppliesOrderRejectResponseDTO'
  /organization:
    get:
      tags:
      - "organization"
      summary: "list organizations"
      description: ""
      operationId: "organizationList"
      security: 
        - bearerJWT: []
      responses:
        "405":
          description: "Invalid input"
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationListResponseDTO'
  /organization/group-by-supply-type:
    get:
      tags:
      - "organization"
      summary: "group organizations by supply type"
      description: ""
      operationId: "organizationGroupBySupplyType"
      security: 
        - bearerJWT: []
      responses:
        "405":
          description: "Invalid input"
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationGroupBySupplyTypeResponseDTO'
components: 
  securitySchemes:
    bearerJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT        
  schemas:
    UserSignUpRequestDTO:
      type: "object"
      required: 
        - email
        - password
      properties:
        first_name:
          type: "string"
        last_name:
          type: "string"
        phone:
          type: "string"
        company:
          type: "string"
        position:
          type: "string"
        locality:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"
      xml:
        name: "data"
    UserSignUpResponseDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
      xml:
        name: "data"
    UserSignInRequestDTO:
      type: "object"
      required: 
        - email
        - password
      properties:
        email:
          type: "string"
        password:
          type: "string"
      xml:
        name: "data"
    UserSignInResponseDTO:
      type: "object"
      properties:
        access_token:
          type: "string"
        token_type:
          type: "string"
        expires_in:
          type: "integer"
          format: "int32"
        refresh_token:
          type: "string"
      xml:
        name: "data"
    UserRefreshRequestDTO:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"
      xml:
        name: "data"
    UserRefreshResponseDTO:
      type: "object"
      properties:
        token:
          type: "string"
      xml:
        name: "data"
    UserProfileResponseDTO:
      type: "object"
      properties:
        first_name:
          type: "string"
        last_name:
          type: "string"
        phone:
          type: "string"
        company:
          type: "string"
        position:
          type: "string"
        locality:
          type: "string"
        email:
          type: "string"
      xml:
        name: "data"
    SuppliesOrderCreateRequestDTO:
      type: "object"
      required: 
        - supply_type
        - area_id
      properties:
        supply_type:
          type: "string"
        supply_attributes:
          type: "object"
          additionalProperties:
            type: string
        area_id:
          type: "string"
      xml:
        name: "data"
    SuppliesOrderCreateResponseDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
      xml:
        name: "data"
    SuppliesOrderListResponseDTO:
      type: "object"
      properties:
        items:
          type: "array"
          items:
            $ref: '#/components/schemas/SuppliesOrderListItemResponseDTO'
      xml:
        name: "data"
    SuppliesOrderListItemResponseDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        supply_type:
          type: "string"
        area_id:
          type: "string"
        status:
          type: "string"
          nullable: true
        organization_id:
          type: "integer"
          format: "int32"
          nullable: true
        organization_name:
          type: "string"
        informer_id:
          type: "string"
          nullable: true
      xml:
        name: "data"
    OrganizationListResponseDTO:
      type: "object"
      properties:
        items:
          type: "array"
          items:
            $ref: '#/components/schemas/OrganizationListItemResponseDTO'
      xml:
        name: "data"
    OrganizationListItemResponseDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
      xml:
        name: "data"
    SuppliesOrderGetByIdResponseDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        supply_type:
          type: "string"
        area_id:
          type: "string"
        status:
          type: "string"
          nullable: true
        organization_id:
          type: "integer"
          format: "int32"
          nullable: true
        organization_name:
          type: "string"
        informer_id:
          type: "string"
          nullable: true
        supply_attributes:
          type: "object"
          additionalProperties:
            type: string
      xml:
        name: "supplies-order"
    SuppliesOrderSupplyTypesResponseDTO:
      type: "object"
      properties:
        items:
          type: "array"
          items:
            $ref: '#/components/schemas/SuppliesOrderSupplyTypesItemResponseDTO'
      xml:
        name: "data"
    SuppliesOrderSupplyTypesItemResponseDTO:
      type: "object"
      properties:
        id:
          type: "string"
        description:
          type: "string"
        supply_attributes:
          type: "object"
          additionalProperties:
            type: string
      xml:
        name: "data" 
    SuppliesOrderAcceptRequestDTO:
      type: "object"
      properties:
        supplies_order_id:
          type: "integer"
          format: "int32"
        organization_id:
          type: "integer"
          format: "int32"
      xml:
        name: "data"
    SuppliesOrderAcceptResponseDTO:
      type: "object"
      xml:
        name: "data"
    SuppliesOrderRejectRequestDTO:
      type: "object"
      properties:
        supplies_order_id:
          type: "integer"
          format: "int32"
      xml:
        name: "data"
    SuppliesOrderRejectResponseDTO:
      type: "object"
      xml:
        name: "data"
    OrganizationGroupBySupplyTypeResponseDTO:
      type: "object"
      properties:
        items:
          type: "array"
          items: 
            $ref: '#/components/schemas/OrganizationGroupBySupplyTypeItemResponseDTO'
      xml:
        name: "data"
    OrganizationGroupBySupplyTypeItemResponseDTO:
      type: "object"
      properties:
        supply_type_id:
          type: "string"
        organizations:
          type: "array"
          items: 
            $ref: '#/components/schemas/OrganizationGroupBySupplyTypeItemOrganizationsResponseDTO'
      xml:
        name: "data"
    OrganizationGroupBySupplyTypeItemOrganizationsResponseDTO:
      type: "object"
      properties:
        organization_id:
          type: "integer"
          format: "int32"
        organization_name:
          type: "string"
      xml:
        name: "data"
